{% set version = "1.0.0" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: c23405d15b55af22784460fa025b216f528199d968cb95e202ff2eca05545365 

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.30
    - pkg-config #[osx]
  host:
    - gsl
    - openblas
    - zlib
    - bzip2
    - xz
    - clangdev
  run:
    - gsl
    - openblas
    - zlib
    - bzip2
    - xz
    - clangdev

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
